# Te damos la bienvenida {.unnumbered}

::: enconstruccion
Estos materiales están en desarrollo. 
:::


## Sobre este taller

Este taller está diseñado para introducir a investigadoras/es a GitHub, una potente plataforma para el control de versiones y la colaboración.
Los participantes aprenderán los fundamentos del uso de GitHub para gestionar sus proyectos de investigación, incluyendo cómo crear y gestionar repositorios, realizar un seguimiento de los cambios y colaborar con otras personas.

Además, el taller hará hincapié en la relevancia de GitHub en la promoción de la ciencia abierta, destacando su papel como repositorio de código y datos que apoya la transparencia y la reproducibilidad en la investigación.

Al final del taller, los participantes serán capaces de integrar GitHub en sus flujos de trabajo de investigación, mejorando tanto la colaboración como la difusión abierta del conocimiento científico.

### Objectivos de aprendizaje 

Los objetivos específicos de aprendizaje incluyen:

    - Comprender los conceptos básicos del control de versiones y cómo se aplican a los flujos de trabajo de investigación.

    - Adquirir experiencia práctica en la creación y gestión de repositorios de GitHub.

    - Explorar el uso de GitHub Issues y Projects para gestionar las tareas de investigación y la comunicación dentro de los equipos de investigación.

    - Reconocer los diferentes componentes de un repositorio (readme, licencia, código de conducta, citas, entre otros).


## ¿A quién está dirigido el tutorial?

Este tutorial está dirigido a investigadoras/es de todas las disciplinas interesados en mejorar sus habilidades de gestión de proyectos y colaboración utilizando GitHub.
 Es ideal para quienes forman parte de equipos o grupos de investigación, con cierta familiaridad con los flujos de trabajo de investigación, pero no se requiere experiencia previa con GitHub. 

## Tutoras

- [Beatriz Milz](https://beamilz.com) - Beatriz es una GitHub Star, y actualmente es investigadora post-doctoral en la Universidade Federal do ABC (UFABC), en Brasil. Es doctora en Ciencias Ambientales por la Universidade de São Paulo (USP). Es coorganizadora de R-Ladies São Paulo y editora de revisión de software en rOpenSci».

- [Yanina Bellini Saibene](https://yabellini.netlify.app/) - Yani es una GitHub Star desde 2022. Es Community Manager de rOpenSci, Líder del Proyecto R-Ladies y Vicepresidenta de la Junta Directiva de The Carpentries. Vive en Argentina y es profesora en la Universidad Austral (Argentina). Es organizadora de R-Ladies Santa Rosa y cofundadora y co-presidenta de LatinR. Yani es también formadora e instructora certificada por Posit y The Carpentries. 

## Reutilización y licencia {#sec-licensing}

Todo el material puede reutilizarse libremente bajo los términos de la licencia
[Creative Commons Reconocimiento 4.0 Internacional
Licencia](https://creativecommons.org/licenses/by/4.0/), esto significa que el material
puede utilizarse, reutilizarse y modificarse, siempre que se cite esta fuente.

El código fuente del libro se encuentra en el [repositorio de GitHub]().

Cualquier corrección,
o contribuciones son bienvenidas. Visitá nuestra página
[sobre como contribuir]() para conocer más.


## Convenciones en el libro

El libro esta ordenado en capitulos que abarcan un tema en particular. Dentro del capitulo podemos presentar ejercicios, ejemplos, consejos, advertencias, etc. Para diferenciar estos elementos utilizamos los siguientes bloques:

::: ejercicio
Este es un ejercicio
:::

::: ejemplo
Este es un ejemplo
:::

::: importante
A tener en cuenta!
:::

::: tip
Este es un consejo
:::


## Bibliografia 



## Fuentes

Este libro utilizo como fuentes los siguientes materiales:

* Research Software Engineering with Python: Building software that makes research possible de Damien Irving, Kate Hertweck, Luke Johnston, Joel Ostblom, Charlotte Wickham, y Greg Wilson. Disponible de manera gratuita: https://third-bit.com/py-rse/ 

