---
title: "Profile"
---

En esta leccion vamos a crear una cuenta, si es que no tienes una, revisaremos nuestro perfil en GitHub y aprenderemos a completar informacion importante sobre nuestro trabajo academico y de investigacion. 

## Crear una cuenta en GitHub {-}

GitHub es una de las interfaces y repositorios mundiales mas conocidos y utilizados por quienes desarrollan software y hacen ciencia abierta.  

- Ir a <https://github.com/>.

- Hacer clik en _Registrarse_ or _Sign up_.

- Seguir las indicaciones para crear la cuenta personal.

- Uno de los pasos implica chequear que son una persona y luego validar la direccion de email que usaste para crear la cuenta. 


## Nuestro perfil

Una vez que creamos una cuenta en GitHub, tenemos nuestro perfil publico en internet. 

La página de tu perfil cuenta la historia de tu trabajo a través de los repositorios en los que te interesas, las colaboraciones que has realizado y las conversaciones que has tenido.

Si revisamos [el perfil en GitHub de Yanina](https://github.com/yabellini) vamos a ver un par de cosas interesantes:

- _Informacion general:_  llamamos a esto todo lo que aparece debajo de la foto del perfil.  Nombre, pronombres y una mini bio.  Luego datos de cuantos seguidores tienen y a cuantas personas sigue. Ademas se puede detallar:

  * Lugar de trabajo: @ropensci
  * Localizacion: Santa Rosa, La Pampa, Argentina
  * Zona horaria: 12:51 (UTC -03:00)
  * Sitio web: https://yabellini.netlify.app
  * ORCID: https://orcid.org/0000-0002-4522-7466
  * Diversas redes sociales como Mastodon, LinkedIn, BlueSky y Youtube. 




